enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1
rv-brand = "ReVanced Extended Minimal"

# add 'enabled = false' for not patching a specific app or remove it from the config

# you can use rvmm-config-gen to generate a config

[Music-Extended]
app-name = "YT Music"
patcher-args = "-e 'Custom branding name for YouTube Music' -OappNameNotification='YT Music' -OappNameLauncher='YT Music' -e 'Custom branding icon for YouTube Music' -OappIcon='mmt' -e 'Custom header for YouTube Music' -OcustomHeader='custom_branding_icon' -e 'Visual preferences icons for YouTube Music' -OsettingsMenuIcon='custom_branding_icon' -e 'Settings for YouTube Music' -OsettingsLabel='Revanced Extended Premium'"
patches-source = "anddea/revanced-patches"
cli-source = "inotia00/revanced-cli"
version = "auto"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
arch = "arm64-v8a"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"

[YouTube-Extended]
app-name = "YouTube"
patcher-args = "-e 'Custom branding name for YouTube' -OappName='YouTube' -e 'Custom branding icon for YouTube' -OappIcon='mmt' -e 'Visual preferences icons for YouTube' -OsettingsMenuIcon='custom_branding_icon' -OapplyToAll='true' -e 'Custom Shorts action buttons' -OiconType='outline' -e 'Custom header for YouTube' -OcustomHeader='custom_branding_icon' -e 'Settings for YouTube' -OsettingsLabel='Revanced Extended Premium'"
patches-source = "anddea/revanced-patches"
cli-source = "inotia00/revanced-cli"
version = "auto"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
